# Change these first
owner: Weezevent # Your GitHub organization or username, where this repository lives
repo: status-page # The name of this repository

sites:
    # APIs
  - name: WeezAccess 
    url: https://api.weezevent.com/access/health # butter
    icon: https://cdn.statically.io/gh/Weezevent/status-page/master/assets/weezaccess.png
  - name: WeezPay
    url: https://api.weezevent.com/pay/health # gill
    icon: https://cdn.statically.io/gh/Weezevent/status-page/master/assets/weezpay.png
  - name: WeezTarget
    url: https://api.weezevent.com/target/_BAD # boby
    icon: https://cdn.statically.io/gh/Weezevent/status-page/master/assets/weeztarget.png
    expectedStatusCodes:
      - 403
  - name: WeezCheckpoint
    url: https://api.weezevent.com/checkpoint
    icon: https://weezevent.com/apple-touch-icon.png
    expectedStatusCodes:
      - 401
  - name: WeezPayment
    url: lyria.weezevent.com/health
    icon: https://cdn.statically.io/gh/Weezevent/status-page/0b61f5cb/assets/WeezPayment.png
  - name: Back-office
    url: https://www.weezevent.com/bo/_BAD
  - name: Guichet / Ticket Office
    url: https://guichet.weezevent.com/_BAD
  - name: WeezTicket
    url: https://api.weezevent.com/ticket/health_BAD # pyvar
    icon: https://cdn.statically.io/gh/Weezevent/status-page/master/assets/weezticket.png
  - name: Weezevent
    url: https://weezevent.com/en-gb/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.weezevent.com
  baseUrl: /
  # baseUrl: /your-repo-name
  logoUrl: https://weezevent.com/apple-touch-icon.png
  favicon: https://weezevent.com/apple-touch-icon.png
  name: Weezevent Status
  introTitle: "This is Weezevent’s status page, where you can get updates on how our systems are doing. If there are interruptions to service, we will post a note here."
  introMessage: "If you are experiencing any issues with Weezevent, don’t hesitate to get in touch with us at contact@weezevent.com and we’ll get back to you as soon as we can."

  # real address https://raw.githubusercontent.com/Weezevent/status-page/master/assets/weezevent-theme.css
  # but it is not discovered https://github.com/upptime/upptime/issues/468
  themeUrl: https://cdn.statically.io/gh/Weezevent/status-page/master/assets/weezevent-theme.css
  metaTags:
    - name: "check-meta"
      content: "meta-response"
  css: "h1 { font-size: 24px !important }"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  footer: powered by [Upptime](https://upptime.js.org/)
